:icons: font
:experimental:

=  CC Documentation for the  Mauve VPN Client
A fictional product as template for the n-doc process

This repository contains the developer documentation for the CC evaluation of the 
Mauve VPN Client. This file and the linked resources provide the documentation process and tools.

== Compiling the documents

* Clone the repo

* run `./runmake.sh`

* Result documents are copied to `deliverables`.

Use the Docker image link:https://github.com/n-design/n-doc[n-doc] to compile
the documents to PDF. The root directory of this repo must be mounted under
`/data` in to the container. `runmake.sh` contains this call:

----
docker run --rm  --volume $(pwd):/data ndesign/n-doc make -j4 delivery
----

Use a specific document type (`st`, `tds` etc, see below) instead of delivery to build only a single document.

The optional parameter `-j` controlls the number of threads  (jobs), that GNU Make
starts in parallel. Use the number of cores of your CPU. The more, the faster.

WARNING: Without a number after `-j` GNU Make uses all available resources of
the host system. This might lead to a complete standstill.

== Working on the docments / Structure of the repository

Each developer document has its own subdirectory. The subdirectories have the
same name as the document type: ``ase``, ``adv_tds`` etc. All files that are
specific to that document type reside in that directory. Elements shared between
documents are in the ``common`` directory. Lua programs are in ``lua``.

The documents are modularized. There is a main document that incorporates the
other parts. This main document must have the same name as the directory it
resides in.

=== Minimal Working Examples

The directories ``mwe_tds``, ``mwe_st``, ``mwe_fsp`` and ``mwe_arc`` contain
documents that serve as __Minimal Working Examples__ (MWE, as is common at
ink:https://tex.stackexchange.com/[TeX Stackexchange]). They provide the same
macros as their "bigger" counterparts and serve as test environments for
reproducing bugs or developing smaller chapters that are quicker to compile than
the ADV documents themselves. The main documents ``mwe_tds/mwe_tds.tex``,
``mwe_st/mwe_st.tex`` and ``mwe_fsp/mwe_fsp.tex`` should not be
modified. Instead, create a file ``mwe_<documenttype>_body.tex`` that can be
freely edited. This ``_body`` file is ignored by git so that there are no merge
conflicts that result from experiments. The make goal ``make mwe`` creates
``_body`` files for all MWE-types.


== Build-Management

The goal is to automate the generation of PDF documents and the release
management as far as possible. A combination of tools is used for that:
link:http://personal.psu.edu/jcc8/software/latexmk-jcc/[``latexmk``],
link:https://www.gnu.org/software/make/[``make``] and an assortment of shell
scripts.

``latexmk`` is used at the level of individual documents. To build several
documents at once, ``latexmk`` is combined with ``make``.

The following goals are availavble at the root level ``Makefile``:

[cols="2,4", options="header"]
|===
| Goal      | Purpose

| ``all``      | Creates all PDF-documents and the DB file in their respective directories

| ``delivery`` | Creates all PDF-documents and copies them to the directory ``deliverables``. Documents are renamed so that they have their version number in the name.

| ``ase``  | Creates the Security Target 

| ``fsp`` | Creates the  Funktional Specification (``adv_fsp``)

| ``tds`` | Creates the  Design Specification (``adv_tds``)

| ``arc`` | Creates the  Security Architecture (``adv_arc``)

| ``ate`` | Creates the  Test Coverage (``ate_cov``) 

| ``ref`` | Creates the  List of References (``refliste``)

| ``clean`` | Removes all documents and auxiliary files

| ``mwe`` | Creates the "minimal working examples" (``mwe_*``) and their ``_body`` files.

| ``cleanmwe`` | Removes all documents and auxiliary files for the minimal working examples

|===

The following shell scripts support the build management:

[cols="1,4", options="header"]
|===
| Script | Purpose

| ``scripts/release_documents.sh`` | Creates a document release. Raises the version number and tags the repository.

| ``scripts/renamereleases.sh`` | _Not to be called by the user._ Adds the version number to the file name. Is called from the  ``Makefile``.

| ``scripts/create_release_archive.sh`` | _Not to be called by the user._ Creates an archive with the documents in ``deliverables``. Is called from the  ``Makefile``.

|===


== Release Management

Creating releases is described in a link:doku/creating-releases.adoc[separate document].
