FROM ndesign/n-doc

RUN apt-get update && apt-get -y upgrade \
    && apt-get install -y openjdk-17-jre-headless \
    && apt autoremove --purge && apt clean && rm -rf /var/lib/apt/lists/*

COPY plantuml.tar.gz /
RUN tar x -C / -f /plantuml.tar.gz && rm -f /plantuml.tar.gz

WORKDIR /data

VOLUME ["/data"]
