FROM ndesign/n-doc

RUN apt-get update && apt-get -y upgrade
RUN apt-get install -y openjdk-17-jre-headless

COPY plantuml.tar.gz /
RUN tar x -C / -f /plantuml.tar.gz && rm -f /plantuml.tar.gz

WORKDIR /data

VOLUME ["/data"]
