pipeline {

  agent any

  stages {
    stage("BuildImage") {
      steps {
	sh 'baseimage=n-design/ubuntu ctanmirror=https://mirror.n-design.de/ctan/systems/texlive/tlnet/ make image'
      }
    }
    stage("Publish") {
      steps {
	echo "Publish as Docker-Image"
	withCredentials([usernamePassword(credentialsId: 'Jenkins-LDAP', usernameVariable: 'DOCKER_USERNAME', passwordVariable: 'DOCKER_PASSWORD')]) {
	  sh 'docker login --username=${DOCKER_USERNAME} --password=${DOCKER_PASSWORD} dockerregistry.n-design.de'
	  sh 'make publish'
	}
      }
    }
  }
}
