= n-doc
TeXLive, SQLite, Lua, PlantUML und Werkzeuge für CC-Dokumentation

== Überblick

Die Dateien in diesem Repository bilden die Grundlage für ein Docker Image zum
Erstellen der CC-Dokumentation für den Konnektor. Das Image paketiert eine
reduzierte Fassung von TeXLive, der Datenbank SQLite, Lua und der Bilbiotheken
für die Verwendung von SQLite in Lua. Zum Erstellen der Grafiken in den
Dokumenten wird PlantUML eingebunden. PlantUML braucht ein Java Runtime
Environment.

Die meisten Abhängigkeiten werden beim Erstellen des Containers
heruntergeladen. Lediglich PlantUML wird als Binary mitgeliefert, da es keine
zuverlässigen Downloadpunkte für die verwendeten Bibliotheken zum Erstellen der
PDFs gibt.

== Aufruf

=== Erstellen des Images

Das n-doc Image wird über das Ziel `image` des Makefiles erstellt. Dabei wird
das Image mit dem Label `n-design/n-doc` versehen:

----
make image
----

Das Makefile sieht eine Umgebungsvariable vor, um den kompletten Build ohne
gecachte Zwischen-Images zu erzwingen:

----
CACHE_OPTION=--no-cache make image
----

Zum Übertragen des Images auf den n-design Nexus wird das Ziel `publish`
verwendet:

----
make publish
----


=== Übersetzen der Dokumente

Die Dokumente werden durch den Aufruf von `make` erstellt. Die Quellen der
Dokumente müssen im aktuellen Verzeichnis liegen und das Verzeichnis muss unter
dem Pfad `/data` in den Container gemountet werden:

----
docker run --rm  --volume $(pwd):/data n-design/n-doc make -j4 delivery
----

Statt `delivery` kann auch ein Dokumenttyp (`st`, `tds` etc) verwendet
werden. Der Parameter `-j` steuert die Anzahl der Threads (jobs), die GNU Make
gleichzeitig startet. Hier muss eine Zahl angegeben werden: Die Anzahl der
Builder in der CI-Plattform oder die Anzahl der Cores des Arbeitsplatzrechners.

WARNING: Ohne eine Zahl hinter `-j` verwendet GNU Make die maximalen Ressourcen
des Rechners und startet alle Jobs gleichzeitig. Das führt häufig zum Stillstand
des Systems, weil die simultan laufenden PlantUML Prozesse den Speicher komplett
auslasten.

== Wartung & Pflege

=== Aufbau des `Dockerfiles`

Zentrales Element des Repositorys ist das `Dockerfile`. Es wird ein zweistufiges
Verfahren verwendet, ohne dass ein Zwischenimage persistiert wird. Das erste
Image erstellt die notwendigen Lua-Bibliotheken für den Zugriff auf SQLite und
die Unit-Tests. Das zweite Image kopiert die Bibliotheken an geeignete Stellen
im Dateisystem. Außerdem werden im zweiten Image alle benötigten Tools
installiert. Die Reihenfolge ist so aufgebaut, dass die stabilsten Komponenten
zuerst installiert werden, um vom Caching zu profitieren. Dies ist auch der
Grund, weswegen die Installation der zusätzlichen Pakete von TeXLive in
unterschiedliche Schritte aufgeteilt ist: Die schwergewichtigen Pakete wie
Schriftarten werden zuerst installiert. Danach folgen die "kleinen" Pakete. So
muss, wenn ein einzelnes Paket nachinstalliert wird, nur ein schnell zu
erstellender Layer mit kleinen Downloads ersetzt werden.

=== Wartungsarbeiten

* Wenn ein neues TeXLive-Paket verwendet werden soll, muss es in einen der
  `tlmgr install` Aufrufe aufgenommen werden.

* Einmal jährlich (ca. Mai) wird das Jahresrelease von TeXLive
  herausgegeben. TeXLive verwendet rollierende Releases, sodass Releases mit
  geringem Aufwand umzusetzen sind. Im vorliegenden Dockerfile wird die
  Distribution ohne die Jahreszahl in den Pfadnamen installiert. Lediglich wenn es z.B. bei Lua einen Versionswechsel gibt (Wie beim Übergang
  von 2018 auf 2019, bei dem LuaTeX auf Lua 5.3 angehoben wurde),
  müssen ggf. die eingebundenen Bibliotheken angepasst werden.
