.PHONY: tests

tests:
	texlua ./test_common.lua
	texlua ./test_cc_core.lua
	texlua ./test_documents.lua
	texlua ./test_bridge_common.lua
	texlua ./test_bridge_cc_core.lua
	texlua ./test_bridge_documents.lua
	texlua ./test_table_generator.lua

