$hash_calc_ignore_pattern{'luc'}='^';

push @generated_exts, "lol", "run.xml", 'glo', 'gls', 'glg', 'acn', 'acr', 'alg', "xdy", "appnote";

$pdf_mode = 4; $postscript_mode = $dvi_mode = 0;
$bibtex_use = 2;
$pdflatex = "pdflatex --shell-escape %O %S";
$lualatex = "lualatex --shell-escape %O %S";
