CREATE TABLE spd ( `label` TEXT, `name` TEXT, `description` TEXT, `PP` TEXT, PRIMARY KEY(`label`) );
CREATE TABLE spd_obj ( `spd` TEXT, `obj` TEXT, `rel` TEXT, FOREIGN KEY(`spd`) REFERENCES `spd`(`label`), FOREIGN KEY(`obj`) REFERENCES `obj`(`label`) );
CREATE TABLE subsystems ( `label` TEXT, `name` TEXT, `plainname` TEXT, PRIMARY KEY(`label`) );
CREATE TABLE modules ( `subsystem` TEXT, `label` TEXT, `name` TEXT, `plainname` TEXT, PRIMARY KEY(`subsystem`,`label`), FOREIGN KEY(`subsystem`) REFERENCES `subsystems`(`label`) );
CREATE TABLE interfaces ( `subsystem` TEXT, `module` TEXT, `label` TEXT, `name` TEXT, PRIMARY KEY(`subsystem`, `module`, `label`), FOREIGN KEY(`subsystem`) REFERENCES `subsystems`(`label`) , FOREIGN KEY(`module`) REFERENCES `modules`(`label`) );
CREATE TABLE sfr ( `label` TEXT, `name` TEXT, `description` TEXT, `src` TEXT, PRIMARY KEY(`label`) );
CREATE TABLE sfr_subsfr ( `sfr` TEXT, `subsfr` TEXT, FOREIGN KEY(`sfr`) REFERENCES `sfr`(`label`) );
CREATE TABLE sfr_module ( `sfr` TEXT, `relationtype` TEXT, `subsystem` TEXT, `module` TEXT, `purpose` TEXT, FOREIGN KEY(`sfr`) REFERENCES `sfr`(`label`) );
CREATE TABLE sf ( `label` TEXT, `name` TEXT, `description` TEXT, PRIMARY KEY(`label`) );
CREATE TABLE sfr_sf ( `sfr` TEXT,  `sf` TEXT, FOREIGN KEY(`sfr`) REFERENCES `sfr`(`label`), FOREIGN KEY(`sf`) REFERENCES `sf`(`label`) );
CREATE TABLE obj ( `label` TEXT, `name` TEXT, `description` TEXT, `PP` TEXT, PRIMARY KEY(`label`) );
CREATE TABLE sfr_obj ( `sfr` TEXT, `obj` TEXT, FOREIGN KEY(`sfr`) REFERENCES `sfr`(`label`), FOREIGN KEY(`obj`) REFERENCES `obj`(`label`) );
CREATE TABLE tsfi ( `label` TEXT, `name` TEXT, `relationtype` TEXT, PRIMARY KEY(`label`) );
CREATE TABLE sfr_tsfi ( `sfr` TEXT,  `tsfi` TEXT, `purpose` TEXT, FOREIGN KEY(`sfr`) REFERENCES `sfr`(`label`), FOREIGN KEY(`tsfi`) REFERENCES `tsfi`(`label`) );
CREATE TABLE errors ( `code` TEXT, `type` TEXT, `severity` TEXT, `msg` TEXT, PRIMARY KEY(`code`) );
CREATE TABLE testcases ( `label` TEXT, `block` TEXT, `name` TEXT, PRIMARY KEY(`label`) );
CREATE TABLE testcase_module ( `testcase` TEXT, `subsystem` TEXT, `module` TEXT, FOREIGN KEY(`testcase`) REFERENCES `testcases`(`label`), FOREIGN KEY(`subsystem`) REFERENCES `subsystems`(`label`) , FOREIGN KEY(`module`) REFERENCES `modules`(`label`) );
CREATE TABLE testcase_sfr ( `testcase` TEXT, `sfr` TEXT, FOREIGN KEY(`sfr`) REFERENCES `sfr`(`label`), FOREIGN KEY(`testcase`) REFERENCES `testcases`(`label`) );
CREATE TABLE testcase_tsfi ( `testcase` TEXT, `tsfi` TEXT, FOREIGN KEY(`tsfi`) REFERENCES `tsfi`(`label`), FOREIGN KEY(`testcase`) REFERENCES `testcases`(`label`) );
CREATE TABLE bundles ( `bundle` TEXT, PRIMARY KEY(`bundle`) );
CREATE TABLE bundle_module ( `bundle` TEXT, `subsystem` TEXT, `module` TEXT, FOREIGN KEY(`bundle`) REFERENCES `bundles`(`bundle`), FOREIGN KEY(`subsystem`) REFERENCES `subsystems`(`label`) , FOREIGN KEY(`module`) REFERENCES `modules`(`label`));
CREATE TABLE bundle_status ( `label` INTEGER, `name` TEXT, PRIMARY KEY(`label`)  );
