:icons: font
:experimental:

= Erstellen eines CC-Doku Releases

Das Erstellen eines Releases der CC-Dokumentation ist ein mehrschrittiger
Prozess, der in unregelmäßigen Abständen durchgeführt wird. Dieses Dokument
beschreibt die notwendigen Schritte, jeweils mit den notwendigen Vorbedingungen.

== Prüfen der Dokumente

Vor einem Release sollten möglichst alle "To Do" Einträge entfernt werden. Auch
dürfen keine unaufgelösten Referenzen ("... is undefined") in den Dokumenten
stehen.

=== Vorbedingungen

* Alle Dokumente müssen als PDF Dokumente aktuell übersetzt vorliegen.

=== Durchführung

* Das Skript `scripts/sanity_check.sh` durchsucht die PDF-Dokumente nach den
  Textstellen "is undefined" und "To Do". Treffer werden auf der Kommandozeile
  ausgegeben.


== Versionieren / Taggen

Das zentrale Element des Prozesses ist das Vergeben einer Versionsnummer für die
auszuliefernden Dokumente. Das Verfahren sieht vor, dass die verschiedenen
Dokumente unterschiedliche Versionen tragen. Die Verfahren ist an das
Versionierungsschema von Maven angelegt: Arbeitsversionen tragen "-SNAPSHOT" in
der Versionsnummer. Beim Release wird "-SNAPSHOT" entfernt. Damit ist der
Dokumentenstand, der die Version ausmacht, festgelegt. Im nächsten Schritt wird
die Versionsnummer erhöht und "-SNAPSHOT" wieder angehängt.

Außerdem wird für jedes Dokument ein Git-Tag gesetzt, aus dem Dokumentenname und Version hervorgehen.

=== Vorbedingungen

* Das Repository muss komplett commitet sein.

* Der Branch "master" muss ausgecheckt sein.

* Der Benutzer, der die Version erstellt, muss die Rolle _Maintainer_ auf das
  Repository haben -- ansonsten schlägt der ``push`` fehl.


=== Durchführung

==== Setzen der Version

Das Skript ``scripts/release_documents.sh`` automatisiert diesen Prozess
weitestgehend. Das Skript wird mit den Kennungen der zu taggenden Dokumente
aufgerufen (s. Beispiel unten). Es ist nicht notwendig, eine Versionsnummer zu
übergeben, diese wird für jedes Dokument aus ``common/db/releases.csv``
ermittelt. Diese Datei wird von diesem Skript auch angepasst.  Mit dem
Kommandozeilenschalter `--all` werden die Versionen aller Dokumente angehoben,
ohne dass der genaue Dokumentname übergeben werden muss.

Das Skript prüft die Vorbedingungen für das Repository, stellt die zu
vergebenden Versionsnummern fest und gibt die Aktionen aus. Der Benutzer muss
mit ``yes`` bestätigen, ansonsten endet der Prozess.

Ein Beispielaufruf, in dem das Security Targets und das ADV_TDS Dokument
neu versioniert werden (Dieser Beispielaufruf zeigt die Situation, in der der
Benutzer nicht berechtigt ist, den Push auszuführen.):

----
[cc-mauvevpn (master)]$ ./scripts/release_documents.sh ase adv_tds // <1>
Tagging ase with ASE/v1.3 (and updating from 1.3-SNAPSHOT to 1.4-SNAPSHOT)
Tagging adv_tds with ADV_TDS/v1.0 (and updating from 1.0-SNAPSHOT to 1.1-SNAPSHOT)
Enter 'yes' to Continue -> yes  // <2>
Tagging ase with ASE/v1.3
Tagging adv_tds with ADV_TDS/v1.0
Counting objects: 10, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (10/10), done.
Writing objects: 100% (10/10), 857 bytes | 857.00 KiB/s, done.
Total 10 (delta 9), reused 0 (delta 0)
remote: GitLab: You are not allowed to push code to protected branches on this project.
To gitlab.mauvecorp.com:cc/cc-mauvevpn.git
 ! [remote rejected] master -> master (pre-receive hook declined) // <3>
error: failed to push some refs to 'git@gitlab.mauvecorp.com:cc/cc-mauvevpn.git'
Counting objects: 8, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (8/8), done.
Writing objects: 100% (8/8), 756 bytes | 756.00 KiB/s, done.
Total 8 (delta 6), reused 0 (delta 0)
To gitlab.mauvecorp.com:cc/cc-mauvevpn.git
 * [new tag]         ADV_TDS/v1.0 -> ADV_TDS/v1.0
 * [new tag]         ASE/v1.3 -> ASE/v1.3
----
<1> Aufruf des Skripts durch den Benutzer
<2> Sicherheitsabfrage, mit `yes` beantworten, sonst Abbruch
<3> Fehlermeldung, wenn der Benutzer nicht die Rolle _Master_ auf dem Repository hat.
