:icons: font
:experimental:

= Creating a Document Release

Creating a document release is a multi-step process. This document describes the
necessary steps and their preconditions.

== Checking the Documents

Before the documents are released, they should be thoroughly checked. All "to
do" entries should be removed. Also, there should be no unresolved references in
the documents ("... is undefined").

=== Preconditions

* All documents have been compiled to PDF.

=== Execution

* The script `scripts/sanity_check.sh` searches all PDF documents for
  occurrences of "is undefined" and "To Do" and prints the file names to the
  console.


== Versioning / Tagging

The central part of the release process is increasing the version number for the
documents to be released. Every document has its own version number independent
of the version number of other documents. The release process and versioning
scheme is similar to Apache Maven, a popular build tool in the Java world.

Documents are in a snapshot state most of the time. Only when documents are
released, they have a non-snapshot state. However, immediately after the
release, they enter a snapshot state again. Technically, this is shown by adding
the qualifier `-SNAPSHOT` to the version number. When a document is released,
the qualifier `-SNAPSHOT` is removed. Immediately after that, the version number
is increased and the qualifier `-SNAPSHOT` is appended to the
version. Furthermore, each document is tagged with a git tag.

The script ``scripts/release_documents.sh`` automates the release process. The
script is called from the root directory of the repository. The name of each
document to be released is an argument on the command line (see below for
examples). It is not necessary to provide a version number. The version number
is calculated from the database file ``common/db/releases.csv``. The release
script updates this file.

The script verifies the preconditions. If they are not fulfilled, the script
aborts. The script calculates the version number and prints all actions to the
console. The user must confirm these actions with `yes`, otherwise the script
aborts and the release process terminates without any changes to the repository.


=== Preconditions

* The repository state must be committed and the workspace must be clean (as reported by `git status`)

* The `main` branch must be checked out.

* The user creating the release must be authorized to push to the `main`
  branch. Often, the `main` branch is protected on the remote repository,
  resulting in failed pushes if the user does not have necessary privileges.

=== Execution

==== Increasing the Version Number




Ein Beispielaufruf, in dem das Security Targets und das ADV_TDS Dokument
neu versioniert werden (Dieser Beispielaufruf zeigt die Situation, in der der
Benutzer nicht berechtigt ist, den Push auszuführen.):

----
[cc-mauvevpn (master)]$ ./scripts/release_documents.sh ase adv_tds // <1>
Tagging ase with ASE/v1.3 (and updating from 1.3-SNAPSHOT to 1.4-SNAPSHOT)
Tagging adv_tds with ADV_TDS/v1.0 (and updating from 1.0-SNAPSHOT to 1.1-SNAPSHOT)
Enter 'yes' to Continue -> yes  // <2>
Tagging ase with ASE/v1.3
Tagging adv_tds with ADV_TDS/v1.0
Counting objects: 10, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (10/10), done.
Writing objects: 100% (10/10), 857 bytes | 857.00 KiB/s, done.
Total 10 (delta 9), reused 0 (delta 0)
remote: GitLab: You are not allowed to push code to protected branches on this project.
To gitlab.mauvecorp.com:cc/cc-mauvevpn.git
 ! [remote rejected] master -> master (pre-receive hook declined) // <3>
error: failed to push some refs to 'git@gitlab.mauvecorp.com:cc/cc-mauvevpn.git'
Counting objects: 8, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (8/8), done.
Writing objects: 100% (8/8), 756 bytes | 756.00 KiB/s, done.
Total 8 (delta 6), reused 0 (delta 0)
To gitlab.mauvecorp.com:cc/cc-mauvevpn.git
 * [new tag]         ADV_TDS/v1.0 -> ADV_TDS/v1.0
 * [new tag]         ASE/v1.3 -> ASE/v1.3
----
<1> Aufruf des Skripts durch den Benutzer
<2> Sicherheitsabfrage, mit `yes` beantworten, sonst Abbruch
<3> Fehlermeldung, wenn der Benutzer nicht die Rolle _Master_ auf dem Repository hat.
