= Schritt-für-Schritt Anleitung zum Verwenden des Modul-Templates

* Erstellen eines Branches. Die Namenskonvention ist: ``<bearbeiter>_<subsystem>_<modul>``.

* Verzeichnis für Subsystem anlegen, falls noch nicht vorhanden. Die Beschreibung der Module liegt in ``/tds/module/<subsystem>/<modul>``. Die Verzeichnisse ``<subsystem>`` und ``<modul>`` müssen ggf. noch angelegt werden

* Template-Datei in das Zielverzeichnis kopieren:
  ``module_<subsystem>_<module>.tex``

* Einbinden der neuen Datei in ``tds_module.tex``, von der aus alle
  Modulbeschreibungen integriert werden. Ggf. hier die Überschrift für
  das Subsystem einfügen.


== Erstellung eines neuen Moduls

* Suche/Ersetze ``subxxx.modyyy`` durch das Label des
  Subsystems/Moduls.

* Entscheidung: Ist das Modul SFR-enforcing oder SFR-supporting? In
  ``\moduleKapitel{}{}`` eintragen

** ``\enfc{}`` -> SFR-enforcing
** ``\supp{}`` -> SFR-supporting

* Die Modulbeschreibung erstellen, vgl. Kommentare in Template-Datei.

* Die Schnittstellen beschreiben, vgl. Kommentare in Template-Datei. 

TIP: Die CC verlangt, dass Schnittstellen _nach_ den Abläufen
stehen. Dennoch kann es für Strukturierung der eigenen Gedanken
hilfreich sein, die Schnittstellen zuerst zu beschreiben, da die
Abläufe immer von den Schnittstellen ausgehen.

* Die Abläufe des Moduls beschreiben, vgl. Kommentare in Template-Datei.

== Übernahme eines bereits beschriebenen Moduls

Die Grundlage für die Migration von Word nach LaTeX ist eine
Konvertierung der docx-Datei mit Pandoc. Das so konvertierte Dokument
ist eine gute Ausgangsbasis, braucht allerdings noch Einiges an
Handarbeit, bis das Dokument in vernünftiger Qualität umgesetzt ist.


Dabei geht es -- neben der Revision der Texte -- um die
Umsetzung/Verwendung von Makros.

Bei den bisher übernommenen Textteilen hat sich das folgende Vorgehen bewährt:

* Erstellen und Einbinden einer neuen Moduldatei wie oben beschrieben.

* Kopieren der einzelnen Abschnitte (Beschreibung, Abläufe,
  Schnittstellen) aus der Ursprungsdatei. Die roh-konvertierten, noch
  unbehandelten Texte liegen in der Datei ``tds_module.tex`` unterhalb
  der Markierung ``%% ab hier noch unbearbeitet / here be dragons!``.

== Zu verwendende Makros

Bei der Erstellung der Modulbeschreibungen im TDS müssen besonders die
folgenden Makros verwendet werden:

* ``\tds{}`` und ``\tdslink{}`` für die Kennzeichnung von Subsystemen,
   Modulen und Schnittstellen. ``\tdslink{}`` erzeugt einen Hyperlink
   auf das Subsystem/Modul/Schnittstelle.

* ``\sfr{}`` und ``\sfrlink{}`` für die Kennzeichnung von
  Sicherheitsanforderungen. ``\sfrlink{}`` erzeugt einen Hyperlink auf
  das SFR. Wenn das SFR im Dokument nicht definiert ist, wird eine
  Fehlermeldung im PDF-Dokument erzeugt: ``<sfrname> is undefined``.

IMPORTANT: In den Namen der SFR dürfen die Unterstriche nicht maskiert
werden. ``\sfr{fcs_cop.1}`` ist korrekt, ``\sfr{fcs\_cop.1}`` führt zu
einer Fehlermeldung beim Übersetzen.

* ``\java{}`` für die Kennzeichnung von Java-Typen.

TIP: Java-Typen sind für die Silbentrennung nicht ohne hilfe zu
trennen. Um zu volle oder zu leere Zeilen zu vermeiden, empfiehlt es
sich, bei ``\java{}`` passende Trennstellen vorzugeben:
``\java{ICard\-Service.get\-Cards()}``. Solche Trennstellen sind aus
Sicht des Java-Entwicklers vielleicht nicht ganz glücklich, aber immer
noch besser als zentimeterlange Leerräume in einer Zeile.

* ``\todo{}`` für später zu erledigende oder zu prüfende
  Punkte. Übergibt man dem Makro noch ein optionales Argument, wird
  dieser Eintrag in die Liste der offenen Punkte aufgenommen, die am
  Dokumentende steht: ``\todo[Zuordnung des SFR klären]{Die Zuordnung
  der SFR \sfr{fcs_ckm.1} zu diesem Ablauf muss geklärt werden.}``

* ``\keyword{}`` für Schlüsselwörter.

== Einige LaTeX-Kniffe für Sonderzeichen

|===
| `~` | Tilde |  Geschütztes Leerzeichen verhindert einen Umbruch zwischen zwei
Wörtern oder z.B. einer Zahl und der Maßeinheit: User~ID,
01.~Januar~1980
| `--` | Zwei Bindestriche | Gedankenstrich (typographisch: Halbgeviertstrich). In
Abgrenzung zum Bindestrich, der zwei Wörter verbindet.
| `+\-+` | Backslash + Bindestrich | Weicher Trennstrich zur Unterstützung der
Silbentrennung
| `"``  | Shift-2 + rückwärts geneigtes Hochkomma | Öffnendes deutsches
Anführungszeichen
| `"'`  | Shift-2 + Apostroph | Schließendes deutsches Anführungszeichen
| `\,` | Backslash + Komma | Leerzeichen mit reduzierter Breite (Spatium).
Verbindet eine Zahl und eine Maßeinheit, Gruppiert Zahlen in Blöcke
27\,kg, 0\,221\,/\,22\,896-16
|===


== LaTeX Fallstricke

* Overfull/Underfull hboxes: Trennhilfen anbieten (mit `\-`) oder einfach ignorieren...

* Versehentlich angeschalteter Formelmodus: `_`, `#`: + Solche
Sonderzeichen immer mit einem Backslash entwerten (Unterstriche werden
von Makros teilweise maskiert, vgl. die Erklärung zu ``\sfr{}``.
