:icons: font
:experimental:

= Creating a Document Release

Creating a document release is a multi-step process. This document describes the
necessary steps and their preconditions.

== Checking the Documents

Before the documents are released, they should be thoroughly checked. All "to
do" entries should be removed. Also, there should be no unresolved references in
the documents ("... is undefined").

=== Preconditions

* All documents have been compiled to PDF.

=== Execution

* The script `scripts/sanity_check.sh` searches all PDF documents for
  occurrences of "is undefined" and "To Do" and prints the file names to the
  console.


== Versioning / Tagging

The central part of the release process is increasing the version number for the
documents to be released. Every document has its own version number independent
of the version number of other documents. The release process and versioning
scheme is similar to Apache Maven, a popular build tool in the Java world.

Documents are in a snapshot state most of the time. Only when documents are
released, they have a non-snapshot state. However, immediately after the
release, they enter a snapshot state again. Technically, this is shown by adding
the qualifier `-SNAPSHOT` to the version number. When a document is released,
the qualifier `-SNAPSHOT` is removed. Immediately after that, the version number
is increased and the qualifier `-SNAPSHOT` is appended to the
version. Furthermore, each document is tagged with a git tag.

The script `scripts/release_documents.sh` automates the release process. The
script is called from the root directory of the repository. The name of each
document to be released is an argument on the command line (see below for
examples). It is not necessary to provide a version number. The version number
is calculated from the database file `common/db/releases.csv`. The release
script updates this file.

TIP: The script `config/n-doc_bash_completions.sh` defines bash completions for
the `release_documents.sh` script. Hitting kbd:[Tab] will show and complete all
available options and document types. Add `source
/path/to/n-doc/config/n-doc_bash_completions.sh` to your `~/.bashrc` file.

The script verifies the preconditions. If they are not fulfilled, the script
aborts. If the preconditions are met, the script calculates the version number
for each document and prints all actions to the console. The user must confirm
these actions with `yes`, otherwise the script aborts and the release process
terminates without any changes to the repository. If confirmed, all two commits
are created: one in which the `-SNAPSHOT` qualifier is removed, one in which the
version number is increased and the `-SNAPSHOT` qualifier is appended.


=== Preconditions

* The repository state must be committed and the workspace must be clean (as
  reported by `git status`)

* The `main` branch must be checked out.

* The user creating the release must be authorized to push to the `main`
  branch. Often, the `main` branch is protected on the remote repository,
  resulting in failed pushes if the user does not have necessary privileges.

=== Execution

Call the script `scripts/release-documents.sh` with the names of the documents
to be inclusded in the release. The script takes the following arguments.

[cols="1,3"]
|===
| --dry-run       | Don't make acutal changes
| --all           | Release all documents
| --remote <name> | Push changes to remote repo <name>. Default: origin
| --local         | Create a local release, do not push changes
| --assume-yes    | Do not ask for confirmation. DANGEROUS! For use in scripted environment only.
|===

A typical would look like this:

----
./scripts/release_documents.sh --dry-run ase adv_tds
----

This call creates a release of the Security Target ASE and the Design
Specification ADV_TDS. However, this is a dry run so all actions are simulated
only.

----
16:50 $ ./scripts/release_documents.sh --dry-run ase adv_tds
Tagging adv_tds with ADV_TDS/v1.0 (and updating from 1.0-SNAPSHOT to 1.1-SNAPSHOT)
Tagging ase with ASE/v1.0 (and updating from 1.0-SNAPSHOT to 1.1-SNAPSHOT)
Finally, tagging release with Release/01
All changes will be pushed to the remote repository
Enter 'yes' to Continue -> yes
Tagging adv_tds with ADV_TDS/v1.0
git tag -m Increased ADV_TDS version to v1.0 ADV_TDS/v1.0 fe96b9f8c9c4d1d6ff7fc4097dea232e5e907855
git push origin ADV_TDS/v1.0
Tagging ase with ASE/v1.0
git tag -m Increased ASE version to v1.0 ASE/v1.0 fe96b9f8c9c4d1d6ff7fc4097dea232e5e907855
git push origin ASE/v1.0
git tag -m Documents for Release/01 Release/01 fe96b9f8c9c4d1d6ff7fc4097dea232e5e907855
git push origin Release/01
git push origin main
----
