= Using Lua in n-doc

This document explains how the Lua Interpreter in LuaTeX is used during the n-doc typesetting process. If you read German, you might want to read the article in link:https://archiv.dante.de/DTK/PDF/komoedie_2020_3.pdf[Die TeXnische Komödie 02/2020].

== Architecture of the Lua components if the platform

There are several methods for calling the Lua interpreter in LuaTeX. The general
procedure is described very clearly in
link:http://dante.ctan.org/tex-archive/info/luatex/lualatex-doc/lualatex-doc.pdf[the
documentation on CTAN].

The most common use is the `\directlua{}` macro. The arguments of the macro are
handed over to the Lua interpreter and executed there. Furthermore, there are
additional packages that add more ways of providing Lua code. n-doc uses the
link:https://dante.ctan.org/ctan/macros/luatex/latex/luacode/luacode.pdf[Luacode]
package.

In our documents the inclusion of Lua code follows this schema. Example here is
ADV_TDS, all other documents work identically.

``adv_tds/adv_tds.tex``:: is the main document. It includes the common preamble.

``common/common-preamble.tex``:: contains the preamble (everything that comes
before `\begin{document}`) that is identical for all documents. This file
includes all packages and macro definition files. It also sets the module path
for loading Lua libraries.

The Lua code is distributed over several _n-doc packages_:

`common`:: contains utility functions used by all other packages. `common`
  should not contain any logic that is particular to any certification scheme.

`cc_core`:: contains the business logic specific to the CC scheme.

`documents`:: contains business logic for maintaining document versions.

Each of the n-doc packages has the same structure of components. The example
used here is the n-doc package `cc_core`:

`common/cc_core-macros`:: This file contains all the macro definitions for CC
specific use cases.

`common/bridge_cc_core.tex`:: This file contains Lua functions directly related
to the macros in `cc_core-macros.tex`. These functions contain no business logic
but are simple adapters. They represent a bridge to other modules that are
loaded via a `require` statement. These functions call an identically named
function and use `tex.sprint()` to print the result of that call into the output
channel (the PDF file). This is similar to an API.

`lua/bridge_cc_core.lua`:: This module contains the business logic functions
called by `bridge_cc_core.tex`. Functions in this module call the database, the
table generator and other modules. 

`lua/cc_core.lua`:: Contains the code for accessing the database. The module
comprises the table definitions, the provisioning and the queries. There should
not be any business logic in here, just database access.

`lua/test_bridge_cc_core.lua`:: This module contains integration tests for the business
logic. These tests are integration tests, because they test for correctly
generated LaTeX code.

`lua/test_cc_core.lua`:: This module contain the unit tests for the accessing
the database. These tests are unit tests, because they test for correct Lua data
structures.
